title: Ahmad Samiei
author: Ahmad Samiei
description: Ahmad Samiei technical blog
base_url: https://amad.github.io
twitter_handle: Ahmad_Samiei
keywords: Ahmad Samiei, amad, blog, development, software engineering, software design, design patterns, best practices, software architecture
templates:
  - rss.twig
  - blog.twig
  - my-reading-list.twig
  - sitemap.twig
